# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["runner", "toolkit", "day-*"]
resolver = "2"

# [profile.dev]
# opt-level = 1

# [profile.dev.package."*"]
# opt-level = 3
